baseURL = "https://sensolution.id/"
languageCode = "en-us"
title = "Sensolution.ID | Food Sensory and Sensometrics Consulting"
theme = "meghna-hugo"

# Menu
[menu]
    [[menu.nav]]
    name = "About Us"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Service"
    URL = "services"
    weight = 3

    [[menu.nav]]
#    name = "Portfolio"
#    URL = "portfolio"
#    weight = 4

    [[menu.nav]]
    name = "Team"
    URL = "our-team"
    weight = 5

    [[menu.nav]]
#    name = "Pricing"
#    URL = "pricing"
#    weight = 6

    [[menu.nav]]
#    name = "Blog"
#    URL = "blog"
#    weight = 7

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 8

# Site params
[params]
home= "Home"
logo = "images/logo_inversed.png"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBI14J_PNWVd-m0gnUBkjmhoQyNyd7nllA"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/hero.png"
    icon = "tf-ion-play"
    heading = "Sensolution.ID"
    content= "We are pleased to help you to please your consumers!"
    btn = true
    btnText="Explore Us"
    btnURL="#services"

    # call to action
    [params.cta]
    enable = true
    title = "Expertise in Sensory Science and Consumer Studies"
    content = "Don't you wonder how to maintain, improve, design, and search for an ideal food product? Aren't you curious how your product performs and its positioning in competitive market? Don't you eager to hear your consumers' opinion and how to translate it into bussiness action?"
    btnURL = "#"
    btnText = "Start a project with us!"

    # counter
    [params.counter]
    enable = false
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Happy Clients"
        icon = "tf-ion-android-happy"
        count = "+25"

        [[params.counter.counterItem]]
        title = "Projects completed"
        icon = "tf-ion-archive"
        count = "+6"

        [[params.counter.counterItem]]
        title = "Positive feedback"
        icon = "tf-ion-thumbsup"
        count = "95"

        [[params.counter.counterItem]]
        title = "Cups of Coffee"
        icon = "tf-ion-coffee"
        count = "2500"
    
    # footer
    [params.footer]
        copyright = "Themefisher Team"
        copyrightURL = "http://www.themefisher.com"
